@startuml Diagrama de Sequência - Visualizar Pontos de Coleta
actor Morador
participant Sistema
database Banco

Morador -> Sistema: Solicitar visualização de pontos de coleta
Sistema -> Banco: Consultar pontos de coleta disponíveis
Banco --> Sistema: Retornar lista de pontos
Sistema --> Morador: Exibir lista de pontos de coleta
@enduml